BufferOverFlow/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use  Illuminate\Support\Facades\Hash ;

DB::enableQueryLog();



Route::get('/',  'QuestionController@index') ;  
	

// profile routes
Route::get('/profile', [
    'as' =>'profile.show',
    'uses' => 'ProfileController@show'
]);

Route::get('/profile/edit', [
    'as' =>'profile.edit',
    'uses' => 'ProfileController@edit'
]);

Route::post('/profile/edit', [
    'as' =>'profile.store',
    'uses' => 'ProfileController@store'
]);
// Authentication routes...
Route::get('auth/login', [
            'as' => 'login',
            'uses' => 'Auth\AuthController@getLogin'

    ]);

Route::post('auth/login', 'Auth\AuthController@postLogin');

Route::get('auth/logout', [
        'as' => 'logout',
        'uses' => 'Auth\AuthController@getLogout' ,
    ]);

// Registration routes...
Route::get('auth/register', [

    'as' => 'register',
    'uses' =>'Auth\AuthController@getRegister' ,
]);

Route::post('auth/register', 'Auth\AuthController@postRegister');


//questions routes


Route::resource('question' ,'QuestionController' ) ;

Route::get('question/tag/{id}', [
    'as' => 'question.tags' ,
    'uses' => 'QuestionController@questionsWithTag'
] ) ;

// tag routes

Route::resource('tag', 'TagController') ;

// responses routes

Route::resource('response' , 'ResponseController');

// comments routes



Route::post('comment', [
    'as' => 'comment.store' ,
    'uses'=> 'CommentController@store'
]);

Route::post('votes',  [
    'as' => 'vote.add',
    'uses' => 'VoteController@add'
]);

// favorite question  routes

Route::post('favorite/add',  'FavoriteController@add');

BufferOverFlow/app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected  $fillable= [
            "question_title" ,
            "question_body" ,
            "user_id"
        ] ;


     public function user()
     {
         return  $this->belongsTo('App\User') ;
     }

    public function  tags()
    {
        return  $this->belongsToMany('App\Tag') ;
    }
    public function responses ()
    {
        return  $this->hasMany('App\Response') ;
    }

    public function  comments () {
        return  $this->hasMany('App\Comment') ;
    }

    public function  favorites ()
    {
        return  $this->hasMany('App\Favorite') ;
    }


    public function  votes () {
        return $this->hasMany('App\Vote') ;
    }


}

BufferOverFlow/app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Requests;
use App ;
use Auth  ;

use Validator ;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $current_question ;
    public function index()
    {
        $questions= Question::orderBy('created_at', 'desc')->paginate(10) ;
        return  view('questions.all-questions' , compact('questions')) ;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {

        if(Auth::check())
        {
            $tags  = App\Tag::all() ;
            return view('questions.create-question', compact('tags')) ;

        }
        return \Redirect::intended('auth/login')->with('mustLogIn', 'login to be able to ask a question !!');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'question_title' => 'required',
            'question_body' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect('question/create')
                ->withErrors($validator)
                ->withInput();
        }


        $question = new App\Question() ;

        $question->question_title = $request->all()['question_title']  ;
        $question->question_body = $request->all()['question_body']  ;
        $question->user_id =Auth::id() ;
        $question->created_at = \Carbon\Carbon::now() ;

        $question->save();
        $question->tags()->attach($request->input('tags')) ;

        return  redirect('question/create')->with('questionCreated' , 'question created !! ') ;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->current_question = $id ;
        $question = App\Question::find($id)  ;

        $tags =  $question->tags()->get()->toArray();

        $categories = $question->tags->modelKeys();
        $relatedQuestions = Question::whereHas('tags', function ($q) use ($categories) {
            $q->whereIn('tags.id', $categories);
        })->where('id', '<>', $id)->get();

        $owner = $question->user()->first()->toArray() ;

        $favorited = 0;
        $user_f =  App\Favorite::where(['user_id' => Auth::id(), 'question_id'=> $id])->first() ;
        if($user_f) $favorited =1 ;

        $conditions = ['questions.id' => $id ,  'comments.response_id' => 0] ;
        $question_comments =\DB::table('users')
                                ->join('questions', 'users.id', '=', 'questions.user_id')
                                ->join('comments', 'comments.question_id', '=', 'questions.id')
                                ->select('users.login', 'comments.comment_text', 'comments.created_at', 'comments.updated_at')
                                ->where($conditions)
                                ->get() ;
        $question_vote =  App\vote::select('vote_value')
                                    ->where('question_id' , '=',  $id)
                                    ->first();
        if($question_vote === null) $question_vote =0 ;
        else $question_vote = $question_vote->toArray()['vote_value'] ;

        $responses =\DB::table('users')
            ->join('responses', 'users.id', '=', 'responses.user_id')
            ->join('questions', 'users.id', '=', 'questions.user_id')
            ->select('users.login', 'responses.created_at', 'responses.id','responses.updated_at',  'responses.response_text')
            ->where('responses.question_id' , $id)
            ->groupBy('responses.id')
            ->get() ;

         $response_comments =\DB::table('users')
                         ->join('responses', 'users.id', '=', 'responses.user_id')
                         ->join('comments', 'comments.response_id', '=', 'responses.id')
                         ->select('users.login', 'users.avatar', 'responses.id', 'comments.comment_text', 'comments.created_at', 'comments.updated_at')
                         ->where('responses.question_id' , $id)
                         ->get() ;


        $question->views += 1 ;
        $question->save() ;
        return view('questions.question')
                    ->with('question', $question)
                    ->with('question_comments', $question_comments)
                    ->with('question_vote', $question_vote)
                    ->with('owner', $owner)
                    ->with('responses' , $responses)
                    ->with('response_comments',  $response_comments)
                    ->with('favorited' , $favorited)
                    ->with('relatedQuestions' , $relatedQuestions)
                    ->with('tags' , $tags) ;

    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::check())
        {
            if($this->isUserOwnerOfQuestion(Auth::id() , $request->input('question_id')) )
            {
                $q = Question::findOrFail($request->input('request_id')) ;
                $q->validated = 1 ;
                $q->save() ;
            }
            else return  'this question  is not yours,  you cannot validate it  !!' ;
        }
    }

    private function isUserOwnerOfQuestion( $user_id, $question_id)
    {
        $user = App\User::findOrFail($user_id) ;
        $user_questions = $user->questions()->get(array('questions.id'))->toArray() ;

        for($i =0 ; $i<count($user_questions) ; $i++)
        {
            if(in_array($question_id, $user_questions[$i])) {
               return  true  ;
            }
        }
        return  false  ;
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }


    public function validateQuestion(Request $request ) {

        if(Auth::check())
        {
            $q = Question::findOrFail($request->input('request_id')) ;
            $q->validated = 1 ;
            $q->save() ;
        }

    }
    public function  questionsWithTag($tagId ) {

        $tag = App\Tag::findOrFail($tagId) ;

        $qq = $tag->questions()->paginate(10);

        return  view('questions.all-questions' )->with('questions', $qq) ;
    }
    public function  relatedQuestion ()
    {

    }
}

BufferOverFlow/resources/views/questions/all-questions.blade.php
@extends('layouts.layout')

@section('content')
        <h1> list of all questions !! </h1>
        <ul class="list-group panel panel-info">
            @if(count($questions) ==0)
                <h3 style="height: 100px ; padding-left: 20px ; line-height: 3"> there is no question  for this category</h3>
            @endif
            @foreach ($questions as $question )

                <div class="row-fluid">

                    <div class="col-md-3">
                        <ul class="inline stats list-group">
                            <li class="list-group-item">
                                <span>{{$question->views}}</span>
                                views
                            </li>
                            <li class="list-group-item">
                                <span>
                                    @if(count($question->votes()->first()))
                                    {{$question->votes()->first()->toArray()['vote_value']}}
                                    @else {{0}}
                                    @endif
                                </span>
                                votes
                            </li>
                            <li class="list-group-item">
                                <span> {{$question->responses()->count()}}</span>
                                answers
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-9">
                        <h2>  <a href="{{route('question.show', $question->id )}}">
                                {{$question->question_title}}</a></h2>

                            <div class="row-content">{{str_limit($question->question_body, 200)}}
                                <br>
                                @foreach($question->tags()->get() as $tag )
                                    <span class="label label-info">{{$tag->tag_name}}</span>
                                @endforeach

                            </div>
                        <span class="label label-success"> created on : {{$question->created_at}}</span>

                    </div>
                </div>
                    <br><br>
                <div class="list-group-separator"></div>

            @endforeach
        </ul>

        {!! $questions->render()!!}

@stop

BufferOverFlow/resources/views/questions/create-question.blade.php
@extends('layouts.layout')

@section('content')
    <h1> ask a question </h1>


    <div class=" panel panel-info padding" >

            @if(session('questionCreated'))
                <div class="alert alert-info">
                    {{ session('questionCreated') }}
                </div>
            @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            {!! Form::open(array('route' => 'question.store', 'class' => 'form'))  !!}


            <div class="form-group">

                <input type="text" class="form-control"
                       name="question_title" placeholder="title ...">
            </div>

            <div class="form-group">
                    <textarea class="form-control" column="200"
                              name="question_body" id="question_body" placeholder="body ...">

                    </textarea>
            </div>

            @foreach($tags as $tag)

                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="{{$tag->id}}" name="tags[]">
                            <span class="checkbox-material">
                            <span class="check">
                            </span>
                            </span>
                        {{$tag->tag_name}} <br>

                    </label>
                </div>
            @endforeach

            <div class="form-group">
                <button type="submit" class="btn btn-raised btn-primary">submit</button>
            </div>

            {!! Form::close() !!}
        </div>




@stop

BufferOverFlow/resources/views/questions/question.blade.php
@extends('layouts.layout')
@section('content')


    @if(session('responseMade'))
        <div class="alert alert-success">
            {{session('responseMade')}}
        </div>
    @endif
    <div class="row">

    <div class="col-md-8">

        <div class="panel panel-info padding">

            <div class="question">
                <div class="row">
                    <div class="col-md-1">
                        <i class="fa fa-thumbs-up fa-2x vote-up-q "></i>
                        <p class="vote-value zero-margin">{{$question_vote}}</p>

                        <i class="fa fa-thumbs-down fa-2x vote-down-q "></i>

                        <i class="glyphicon glyphicon-ok  validate-question {{($question->validated)? 'validated' :''}}"></i>
                        <i class="fa  fa-2x favorite-question {{ ($favorited == 1) ? 'fa-star' :'fa-star-o' }}"></i>

                    </div>

                    <div class="col-md-11">
                        <h3> {{$question->question_title}} </h3>

                        <div>
                            {{$question->question_body}}

                        </div>

                        <br> <br>
                        @foreach($tags as $tag )
                            <span class="label label-info">{{$tag['tag_name']}}</span>
                        @endforeach
                        <div class="pull-right">

                <span>
                    <i>created by :</i>
                </span>
                     <span class="label label-default">
                        <i> {{$owner['login']}}</i>
                     </span>
                            <br>
                <span>
                    <i>on :</i>
                </span>
                     <span class="label label-default">
                    <i>  {{$owner['created_at']}}</i>
                         </span>
                        </div>

                        <br>
                        <br>
                        <hr class="alert-success">
                    </div>


                    <div id="question-comments-section" style="float:right">

                        <div class="question-comments-show">
                            @foreach($question_comments as $question_comment )
                                <div>
                                    <p> {{$question_comment->comment_text}}</p>
                            <span class="label label-default">
                                commented by :
                                <code> {{$question_comment->login}}</code>
                                on :
                                <code>  {{$question_comment->created_at}}</code>
                            </span>
                                </div>
                            @endforeach
                        </div>

                        <a href="javascript:void(0)"
                           class="btn btn-raised btn-primary add-question-comment zero-pad pull-right">add
                            comment</a>

                        {!! Form::open(array('route' => 'comment.store', 'class'=> 'form hide submit-comment' ))  !!}
                        <div class="form-group">
                            <input type="text" id="comment_text" name="comment_text" class="form-control">
                            <input type="hidden" id="question_id" name="question_id" value="{{$question->id }}">
                        </div>
                        <button type="submit" class="btn btn-sm">add</button>

                        {!! Form::close() !!}
                    </div>
                    <div class="clearfix"></div>


                    <hr>
                </div>
            </div>

            @foreach($responses as $response )
                <div class="response">

                    <div class="row">
                        <div class="col-md-1">
                            <i class="fa fa-thumbs-up fa-2x vote-up-r "></i>
                            <p class="vote-value zero-margin">{{$question_vote}}</p>

                            <i class="fa fa-thumbs-down fa-2x vote-down-r "></i>
                        </div>

                        <div class="col-md-11">
                            <p>
                                {{$response->response_text}}
                            </p>

                        <span class="label label-default">
                            answered by :
                            <code> {{$response->login}}</code>
                            on :
                            <code>  {{$response->created_at}}</code>
                        </span>
                            <br><br>

                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <div class="row">

                                <div class="col-md-9 col-md-offset-3">

                                    <div id="response-comments-section " class="list-group">

                                        <div class="response-comments-show">
                                            @foreach($response_comments as $response_comment )
                                                @if($response_comment->id ==  $response->id)
                                                    <div class="list-group-item">
                                                        <div class="row-picture">
                                                            <img class="circle" src="{{
                                                        str_replace("300x300","300x300",$response_comment->avatar)}}"
                                                                 alt="icon" style="width: 27px;height: 27px;">
                                                        </div>
                                                        <div class="row-content">

                                                            <p class="list-group-item-text"> {{$response_comment->comment_text}}</p>
                                                        <span class="label label-info">
                                                            {{$response_comment->login}}
                                                        </span>
                                                            <span class="label label-info">
                                                                {{$response_comment->created_at}}
                                                            </span>

                                                        </div>
                                                        <div class="list-group-separator"></div>
                                                    </div>

                                                @endif
                                            @endforeach

                                        </div>

                                        <a href="javascript:void(0)"
                                           class="btn btn-raised btn-primary add-response-comment zero-pad pull-right">add
                                            comment</a>
                                        {!! Form::open(array('route' => 'comment.store', 'class'=> 'form hide submit-comment' ))  !!}
                                        <div class="form-group">
                                            <input type="text" id="comment_text" name="comment_text"
                                                   class="form-control"
                                                   placeholder="...">
                                            <input type="hidden" id="question_id" name="question_id"
                                                   value="{{$question->id }}">
                                            <input type="hidden" id="response_id" name="response_id"
                                                   value="{{$response->id }}">
                                        </div>
                                        <button type="submit" class="btn btn-sm">add</button>
                                        {!! Form::close() !!}
                                    </div>
                                    <div class="clearfix"></div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
                <hr>
            @endforeach


            <h4> add a response </h4>

            {!! Form::open(array('route' => 'response.store', 'class'=> 'form'))  !!}
            <div class="form-group">
                <textarea name="response_text" class="form-control" placeholder="...">
                </textarea>
                <input type="hidden" name="question_id" value="{{$question->id}}">
            </div>

            <button type="submit" class="btn btn-raised btn-success">respond</button>
            {!! Form::close() !!}
        </div>
    </div>
    <div class="col-md-4">
        <ul class="list-group panel panel-info padding">
            @if(count($relatedQuestions) ==0)
                <h3 style="height: 100px ; padding-left: 20px ; line-height: 3"> there is no related question !!</h3>
            @endif
            @foreach ($relatedQuestions as $rQuestion )


                    <h2>  <a href="{{route('question.show', $rQuestion->id )}}">
                            {{$rQuestion->question_title}}</a></h2>

                    <div class="row-content">
                        {{str_limit($rQuestion->question_body, 100)}}

                    </div>
            @endforeach
        </ul>
    </div>
    </div>

@stop

BufferOverFlow/resources/views/questions/related-questions.blade.php
@extends('layouts.layout')

@section('sidebar')
  <h3> related questions </h3>
    @foreach($questions as $question )

        <div class="list-group-item">

                <div class="row-content">
                    <h4 class="list-group-item-heading">
                        <a href="{{route('question.show', $question->id )}}">
                            {{$question->question_title}}</a>
                    </h4>
                    <p class="list-group-item-text">{{str_limit($question->question_body, 20)}}</p>
                </div>
            </div>
        <div class="list-group-separator"></div>
    @endforeach
@stop